name: Build and Deploy Docker Containers

on:
  push:
    branches:
      - main  # Trigger on push to the 'main' branch
  pull_request:
    branches:
      - main  # Trigger on PR to the 'main' branch

jobs:
  build_and_deploy:
    runs-on: self-hosted  # Define the environment for the job

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Docker Buildx (for multi-platform builds)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Log in to Docker Hub (or GitHub Container Registry)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 4: Build Docker images for dev, prod, and staging using different Dockerfiles
      - name: Build Docker image for Dev
        uses: docker/build-push-action@v6
        run: |
          docker build -t my-app:dev -f Dockerfile.dev .

      - name: Build Docker image for Prod
        uses: docker/build-push-action@v6
        run: |
          docker build -t my-app:prod -f Dockerfile.prod .

      - name: Build Docker image for Staging
        uses: docker/build-push-action@v6
        run: |
          docker build -t my-app:staging -f Dockerfile.staging .
          
      # Step 5: Install Docker Compose
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.18.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version  # Verify installation

      # Step 6: Build and start containers using Docker Compose
      - name: Set up Docker Compose
        run: |
          docker-compose up -d

      # Optional: Step 7: Verify the running containers
      - name: Check Docker container status
        run: |
          docker ps 
