# This is a basic workflow to help you get started with Actions

name: forth-action file 

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-on-ubuntu:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # here we are runing this pre-build to check the memory state.
      - name: Step 1 - Log the pre-build disc space
        run: df -h
      
      # This step will checkout all the code from the main branch.
      - name: Step 2 - Checkout the main github branch.
        uses: actions/checkout@v4

      # Setting up the Java Development Kit into this step for building the application.
      - name: Step 3 - Set up the JDK 
        uses: actions/setup-java@v4
        with:
          java-version: '23.0.1+11'
          distribution: 'temurin'
          server-id: github
          server-username: GITHUB_ACTOR
          server-password: HUB_TOKEN
          overwrite-settings: true
          job-status: success
          token: ${{ secrets.HUB_TOKEN }}
      
      # In this step basically the maven will build the application with the code and given dependency.
      - name: Step 4 - Building our web application with maven.
        run: echo mvn -B package --file pom.xml

      # Here we will look up the Ubuntu environment variable.
      - name: Step 5 - List the Ubuntu environment variable.
        run: env

  build-on-windows:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # here we are runing this pre-build to check the memory state.
      - name: Step 1 - Log the pre-build disc space
        run: df -h
      
      # This step will checkout all the code from the main branch.
      - name: Step 2 - Checkout the main github branch.
        uses: actions/checkout@v4

      # Setting up the Java Development Kit into this step for building the application.
      - name: Step 3 - Set up the JDK 
        uses: actions/setup-java@v4
        with:
          java-version: '23.0.1+11'
          distribution: 'temurin'
          server-id: github
          server-username: GITHUB_ACTOR
          server-password: HUB_TOKEN
          overwrite-settings: true
          job-status: success
          token: ${{ secrets.HUB_TOKEN }}
      
      # In this step basically the maven will build the application with the code and given dependency.
      - name: Step 4 - Building our web application with maven.
        run: echo mvn -B package --file pom.xml

      - name: Step 5 - Windows execution polocy.
        run: | 
          echo "Get the windows execution polocy.
          Get-ExecutionPolocy

      - name: Step 6 - get the environment variable for windows
        run: env
